### PR TITLE
add Github Actions workflow to run the unit and compat tests

### PR DESCRIPTION
**Pull request by wnienhaus**
This PR fixes issue #44 .

It implements what the previous Travis CI build does, except it:
* Runs on Ubuntu 18.04 instead of 14.04/trusty (On Ubuntu 20.04 the build of binutils-esp32ulp fails)
* Shallow clones repos (`--depth 1`) to save on build time
* Only clones and builds submodules actually required for building the Unix build of MicroPython (instead of doing a full `--recursive` clone) to save on build time

This change also removes the `.travis.yml` file, which is no longer needed.

### CODE REVIEW

**Comment by wnienhaus** [comment]
It appears Github Actions does not run when the workflow file is yet-to-be-merged. But you can see the build succeed on my fork of the repo: https://github.com/wnienhaus/py-esp32-ulp/actions/runs/1087314522 (you can compare the commit id to confirm the build was for the same commit as this PR includes: 7ea24ff)

**Comment by wnienhaus** [comment]
..actually I found this in the docs of Github Actions, which seems to explain why the workflow doesnt run:
> When a first-time contributor submits a pull request to a public repository, a maintainer with write access may need to approve running workflows on the pull request. For more information, see "[Approving workflow runs from public forks.](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)"

**Review by ThomasWaldmann — APPROVED** [review]
looks good, let's see if we can run it...

**Comment by ThomasWaldmann** [comment]
as long as the workflow file is not yet present, it won't run one in the PR.

thus i just merged and now we need another PR to have it running.

Maybe do some dummy commit (and if that works ok, maybe change to ubuntu-latest or ubuntu-20.04).

**Pull request merged**
