### PR TITLE
dummy commit to trigger Github Actions workflow

### PR DESCRIPTION
**Pull request by wnienhaus**
Trying to kick-start Github Actions.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Hmm, maybe we could **either** install all we require (even if it is already there) **or** not install anything which is there already. Currently we are somehow in the middle of these:

We install, but it is there already:
```
bison is already the newest version (2:3.0.4.dfsg-1build1).
flex is already the newest version (2.6.4-6).
libffi-dev is already the newest version (3.2.1-8).
libffi-dev set to manually installed.
pkg-config is already the newest version (0.29.1-0ubuntu2).
```

We do not install, but it is there already(?):
```
build-essentials
```

**Comment by wnienhaus** [comment]
I just tested on a minimal ubuntu 18.04 image (ubuntu:18.04 from docker hub), where no build tools are installed by default, and noticed that the `pkg-config` package already pulls in everything from `build-essential`. So I don't know why I remember needing to install build-essentials (maybe this was different on trusty, which I started with, trying to start as close as possible to the Travis build script as possible before).

But what I now also noticed is that a minimal 18.04 needs a bit more installed than what I have in the current workflow step.

It needs:
* git - to clone the repos we're building from
* libffi-dev + pkg-config - for MicroPython
* python3 - for building mpy-cross from MicroPython
* bison + flex - for building binutils-esp32ulp

So our choices are:
* Install nothing, because the Github Actions image already contains all we need
* Install all of the above packages (even though it'll mostly be a no-op)

Now that you pointed me this way, I would actually lean towards the second, because it should (?) make switching to a different build image in the future easier (it's a form of documentation essentially), e.g. when updating to ubuntu-20.04 or similar (currently not possible because binutils doesnt compile). And it would be more resilient to Github potentially changing the build image.

I think I will update the install step to install all we need (i.e. choice 2 above) and if you prefer the other route, I can fix it later. I think I will also throw in build-essentials, just for good measure.

**Comment by wnienhaus** [comment]
Perhaps also reject this PR, then there's dummy commit cluttering up the history. I will make a new PR for the change to the install step.

**Comment by ThomasWaldmann** [comment]
as desired...

**Pull request closed without merging**
